Week2
moonlimb/search_with_machine_learning_course pull request #2
Opened 2022-02-27 14:57 UTC by moonlimb

2022-02-27 15:24 UTC, moonlimb commented on ltr-end-to-end.sh
> +
```suggestion
```

2022-02-28 11:33 UTC, itanev requested changes
Looks good overall. Several small stuff I noticed.

2022-02-28 11:33 UTC, itanev commented on week2/utilities/build_ltr.py
> +warnings.simplefilter(action='ignore', category=FutureWarning)
It's usually a bad idea to ignore warnings. 😉

2022-02-28 11:33 UTC, itanev commented on week2/utilities/click_models.py
> +    """
I'm not 100% sure myself, but in general, it seems it's retrieving the grade groups with the smallest size. I can't say I get the purpose though.

2022-02-28 11:33 UTC, itanev commented on week2/utilities/data_prepper.py
> +        response = self.opensearch.search(body=log_query, index=self.index_name)
What if this throws an exception?

2022-02-28 11:33 UTC, itanev commented on week2/utilities/ltr_utils.py
> +                            "_id": doc_ids
Instead of the `_id` you should use the `terms_field`

2022-03-02 13:05 UTC, moonlimb commented on week2/utilities/data_prepper.py
> +        response = self.opensearch.search(body=log_query, index=self.index_name)
good point, it'd be nice to wrap this with try / catch :)

2022-03-02 15:10 UTC, moonlimb commented on week2/utilities/ltr_utils.py
> +                            "_id": doc_ids
thank you!

2022-03-06 13:41 UTC, merged